import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Custom Vite plugin to generate firebase-messaging-sw.js with injected env vars at build time.
// FCM requires a service worker named "firebase-messaging-sw.js" at the root scope to deliver
// background push notifications when the app is completely closed.
function firebaseMessagingSwPlugin(env) {
  return {
    name: 'firebase-messaging-sw',
    apply: 'build', // Only run during build, not dev
    closeBundle() {
      const apiKey = env.VITE_FIREBASE_API_KEY || ''
      const authDomain = env.VITE_FIREBASE_AUTH_DOMAIN || ''
      const projectId = env.VITE_FIREBASE_PROJECT_ID || ''
      const storageBucket = env.VITE_FIREBASE_STORAGE_BUCKET || ''
      const messagingSenderId = env.VITE_FIREBASE_MESSAGING_SENDER_ID || ''
      const appId = env.VITE_FIREBASE_APP_ID || ''
      const measurementId = env.VITE_FIREBASE_MEASUREMENT_ID || ''

      if (!apiKey || !projectId || !messagingSenderId || !appId) {
        console.warn(
          '[firebase-messaging-sw] Missing Firebase env vars – firebase-messaging-sw.js will not be generated.\n' +
          'Make sure VITE_FIREBASE_API_KEY, VITE_FIREBASE_PROJECT_ID, VITE_FIREBASE_MESSAGING_SENDER_ID, and VITE_FIREBASE_APP_ID are set.'
        )
        return
      }

      const swContent = `// firebase-messaging-sw.js
// Auto-generated by vite.config.js at build time – DO NOT EDIT MANUALLY.
// FCM uses this file to deliver background push notifications when the app is closed.

importScripts('https://www.gstatic.com/firebasejs/10.14.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.14.0/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey: "${apiKey}",
  authDomain: "${authDomain}",
  projectId: "${projectId}",
  storageBucket: "${storageBucket}",
  messagingSenderId: "${messagingSenderId}",
  appId: "${appId}",
  measurementId: "${measurementId}"
});

const messaging = firebase.messaging();

// Handle background messages (app closed or backgrounded)
messaging.onBackgroundMessage(function(payload) {
  console.log('[firebase-messaging-sw] Background message received:', payload);

  const title = payload?.notification?.title || 'New Job Alert';
  const body = payload?.notification?.body || 'A new job posting is available';
  const icon = payload?.data?.companyImage || payload?.notification?.icon || '/pwa-192.png';
  const tag = payload?.notification?.tag || 'new-job';
  const data = payload?.data || {};

  return self.registration.showNotification(title, {
    body,
    icon,
    badge: '/pwa-192.png',
    tag,
    requireInteraction: false,
    data,
    actions: [
      { action: 'open', title: 'View Job' },
      { action: 'close', title: 'Dismiss' }
    ]
  });
});

// Handle notification click
self.addEventListener('notificationclick', function(event) {
  const notification = event.notification;
  const data = notification.data || {};

  notification.close();

  if (event.action === 'close') return;

  const urlToOpen = data.jobId ? '/jobs?jobId=' + data.jobId : '/jobs';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(clientList) {
      const sameOriginClient = clientList.find(function(client) {
        try {
          return new URL(client.url).origin === self.location.origin;
        } catch (e) {
          return false;
        }
      });

      if (sameOriginClient && 'focus' in sameOriginClient) {
        return sameOriginClient.focus().then(function() {
          if ('navigate' in sameOriginClient) {
            return sameOriginClient.navigate(urlToOpen);
          }
        });
      }

      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});
`

      // Resolve relative to the directory where vite.config.js lives (frontend/)
      const outputPath = path.resolve(__dirname, 'dist', 'firebase-messaging-sw.js')

      try {
        fs.writeFileSync(outputPath, swContent, 'utf-8')
        console.log('[firebase-messaging-sw] ✓ Generated dist/firebase-messaging-sw.js')
      } catch (err) {
        console.error('[firebase-messaging-sw] Failed to write firebase-messaging-sw.js:', err)
      }
    }
  }
}

export default defineConfig(({ mode }) => {
  // Load all env vars (including those without VITE_ prefix) for use in the plugin
  const env = loadEnv(mode, process.cwd(), '')

  return {
    plugins: [
      react(),
      firebaseMessagingSwPlugin(env)
    ],
    server: {
      port: 5173,
      proxy: {
        '/api': {
          target: 'http://localhost:5000',
          changeOrigin: true
        }
      }
    }
  }
})
